use_frameworks!

platform :ios, '13.0'

target 'MGActionSheet_Example' do
#  pod 'XMGActionSheet', :path => '../'
#  pod 'FloatingBottomSheet'
  pod 'SnapKit'
  pod 'FloatingBottomSheet', :git => 'https://github.com/OhKanghoon/FloatingBottomSheet.git', :tag => '3.1.0'
  target 'MGActionSheet_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
