use_frameworks!

platform :ios, '13.0'

target 'MGActionSheet_Example' do
  pod 'XMGActionSheet', :path => '../'
  pod 'FloatingBottomSheet'
  target 'MGActionSheet_Tests' do
    inherit! :search_paths

    
  end
end
